plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.sjbtechnologies.awa'
    compileSdk 34

    defaultConfig {
        applicationId "com.sjbtechnologies.awa"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.0.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.lifecycle.runtime.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation "androidx.lifecycle:lifecycle-service:2.7.0"

    implementation libs.kotlinx.coroutines.android

    implementation libs.camera.camera2
    implementation libs.camera.lifecycle
    implementation libs.camera.view

    // MJPEG Server
    implementation 'org.nanohttpd:nanohttpd:2.3.1'

    // External (not in catalog yet)
    implementation 'com.infobip:google-webrtc:1.0.0035529'
    implementation 'io.socket:socket.io-client:2.1.0'
    implementation 'com.karumi:dexter:6.2.3'
}